### ISSUE TITLE
Version on ppa?

### ISSUE THREAD

**Issue by peteruithoven** [nallath/PostProcessingPlugin#29]
@thopiekar I noticed this plugin is included separately in [your Cura ppa ](https://launchpad.net/~thopiekar/+archive/ubuntu/cura). I've updated my system, giving me (I think) the latest version of this plugin:
```
Package: cura-extra-plugin-postprocessing
Version: 2.3.99-truely-2.3.1-0~201611281637~106~ubuntu16.04.1
Priority: optional
Section: science
Source: cura-extra-plugins
Maintainer: Thomas Karl Pietrowski <thopiekar@googlemail.com>
Installed-Size: 117 kB
Depends: cura-plugin-api-3
Download-Size: 24,5 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/thopiekar/cura/ubuntu xenial/main amd64 Packages
Description: Cura plugin - PostProcessing
 For more info see: https://github.com/nallath/PostProcessingPlugin
```
But what does this contain? I notice it doesn't include my merged (to master) pull request, which already included in the latest release / tag (https://github.com/nallath/PostProcessingPlugin/releases/tag/2.3.1).

I can never wrap my head around Lauchpad... I'd love to get more information about `cura-extra-plugins` which seems to be the source of cura-extra-plugin-postprocessing. After clicking through lot's of links I found this page: http://ppa.launchpad.net/thopiekar/cura/ubuntu/pool/main/c/cura-extra-plugins/ which indicates that this plugin was modified only days ago. 
Is there a separate git repo for cura-extra-plugins?

**Comment by peteruithoven** [comment]
I just found this repo: https://github.com/thopiekar/Cura-packaging/tree/master/2.3/Cura-extra-plugins where I can probably learn more. Why not mention it on the Launchpad ppa page?

**Comment by thopiekar** [comment]
Hey @peteruithoven ,

first of all thank you for your interest in my PPA. The package contains all content of the 2.3.1 tag.
I checked whether your changes are really in the 2.3.1 tag, but I couldn't find them.
* https://github.com/nallath/PostProcessingPlugin/commits/2.3.1
On the other hand there are commits from you in [master]:
* https://github.com/nallath/PostProcessingPlugin/commits/master

So obviously you'll be able to find your changes in the master PPA.
There are three options:
1. [Cherry-pick](https://git-scm.com/docs/git-cherry-pick) your changes into a fresh copy of the branch 2.3, make another PR and ask for an update of the 2.3.1 tag.
2. Go to the master PPA site and download the deb file manually.
3. Switch to the master PPA, take the risk of broken builds and wait until the next stable release.

For more info see https://github.com/thopiekar/Cura-packaging. There is a list in the README of all recipes being used. You probably noticed the `2.3.99-truely-2.3.1-0` in the version. Well, that's due to an mistake I made when converting all recipes from Bzr to Git.

.. Oops, my answer is a bit late..

**Comment by thopiekar** [comment]
@peteruithoven Good question. I'll add a link into the both PPA pages.

**Comment by peteruithoven** [comment]
Ah apologies. I saw the `Better error reporting` commit, which was more recent than my merge. But looks like the tag was created from a 2.3 branch, which didn't include my pr's but does include that `Better error reporting` commit. I guess I'm a bit too used to [one git branching model](http://nvie.com/posts/a-successful-git-branching-model/). 

Thanks for all the info, I still have a lot to learn when it comes to packaging.

**Comment by thopiekar** [comment]
No problem. Feel free to report problems at https://github.com/thopiekar/Cura-packaging.
There are of course enough things, which need to be done, like adding proper package descriptions and other minor problems.
Feel free to send PRs there, if you like :wink:
