### ISSUE TITLE
PauseAtHeight broken in 2.4

### ISSUE THREAD

**Issue by AmedeeBulle** [nallath/PostProcessingPlugin#38]
There is a typo in [PauseAtHeight](https://github.com/nallath/PostProcessingPlugin/blob/2.4/scripts/PauseAtHeight.py#L40) - ammount instead of amount

It is a bit strange because it has been fixed in master 6 months ago, but it is still in 2.4 and 2.5 branches for that particular line.

**Comment by Ghostkeeper** [comment]
It doesn't seem to be in the 2.5 branch: https://github.com/nallath/PostProcessingPlugin/blob/2.5/scripts/PauseAtHeight.py#L38

It is in 2.4 though, which was branched off in December iirc. I'm guessing that whoever made that branch didn't pull this repository locally before he did so. Anyway, it seems fixed in 2.5 now.

**Comment by Ghostkeeper** [comment]
There is still the typo "fillament" two lines lower though... I'll patch that up.
